// Code generated by sqlc-pg-gen. DO NOT EDIT.

package contrib

import (
	"github.com/stephenwithav/sqlc/pkg/sql/ast"
	"github.com/stephenwithav/sqlc/pkg/sql/catalog"
)

var funcsTcn = []*catalog.Function{
	{
		Name:       "triggered_change_notification",
		Args:       []*catalog.Argument{},
		ReturnType: &ast.TypeName{Name: "trigger"},
	},
}

func Tcn() *catalog.Schema {
	s := &catalog.Schema{Name: "pg_catalog"}
	s.Funcs = funcsTcn
	return s
}
